language: java
jdk:
- oraclejdk8
sudo: false

before_install:
- cd judge-backend
- pip install --user codecov

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)