version: "2"
services:
 web-back:
  build:
   context: judge-backend
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
 db:
  build:
   context: judge-db
   dockerfile: Dockerfile
  ports:
   - "5432:5432"
 go:
  build:
   context: judge-external-runner/go
   dockerfile: Dockerfile
  ports:
   - "8123:8123"
 web-front:
  build:
   context: judge-frontend
   dockerfile: Dockerfile
  ports:
   - "3008:3008"
