export const BACKEND_ADDRESS = "http://localhost:8080/";
export const JUDGE_ENDPOINT = "judge/submit";
export const ADD_STUDENT_ENDPOINT = "student/add";
export const SUBMISSION_ENDPOINT = "submission/getAll";
export const SOLUTION_ENDPOINT = "submission/getAllForProblem?id=";
export const PROBLEM_ENDPOINT = "problems/getAll";
export const PROBLEM_CREATOR_ENDPOINT = "problems/add";
export const PROBLEM_ID_ENDPOINT = "problems/getByID?id=";
export const PROBLEM_TEMPLATE_ENDPOINT = "problems/getTemplate";